# Generated by Django 2.1.3 on 2018-11-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181123_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=2, upload_to='static/'),
            preserve_default=False,
        ),
    ]
